### ISSUE TITLE
Issues with parsing

### ISSUE THREAD

**Issue by kwiha** [mnrkbys/norimaci#1]
Hi, thanks for releasing this awesome tool. There seems to be some parsing errors when converting the openBSM data.

`tester@testers-Mac norimaci % sudo python3 ./norimaci.py -m openbsm -o ./out/
Password:

--===[ Norimaci v0.1.0
--===[ Minoru Kobayashi [@unkn0wnbit]
[*] Launching OpenBSM agent...
[*] When runtime is complete, press CTRL+C to stop logging.
^C
[*] Termination of OpenBSM agent commencing... please wait
[*] Converting OpenBSM data ...
Error: Unknown tag: osx / path,/var/folders/m8/4ldr8lq97bb2wsxfd78572kw0000gn/C/com.apple.Safari.SafeBrowsing/Google/malware,osx,url_expression.tmp,path,/private/var/folders/m8/4ldr8lq97bb2wsxfd78572kw0000gn/C/com.apple.Safari.SafeBrowsing/Google/malware,osx,url_expression.tmp,attribute,100644,tester,staff,16777220,212528,0,path,/var/folders/m8/4ldr8lq97bb2wsxfd78572kw0000gn/C/com.apple.Safari.SafeBrowsing/Google/malware,osx,url_expression,path,/private/var/folders/m8/4ldr8lq97bb2wsxfd78572kw0000gn/C/com.apple.Safari.SafeBrowsing/Google/malware,osx,url_expression,subject,tester,tester,staff,tester,staff,1577,100006,50331650,0.0.0.0,return,success,0,identity,1,com.apple.Safari.SafeBrowsing,complete,,complete,0x8ebe7dc23beb5ac0f0b075414edb3e4327bfe819,trailer,649,
[!] Fatal: Failed to run data converter: Command '['python3', '/Users/tester/Downloads/norimaci/./openbsmconv.py', '-p', '/Users/tester/Downloads/norimaci/out/Norimaci_25_Jan_20__15_33_675474.proclist', '--with-failure-socket', '-f', '/Users/tester/Downloads/norimaci/out/Norimaci_25_Jan_20__15_33_675474.bsm', '-o', '/Users/tester/Downloads/norimaci/out/Norimaci_25_Jan_20__15_33_675474.json', '--force']' returned non-zero exit status 1.
[Norimaci_25_Jan_20__15_33_675474.bsm.zip](https://github.com/mnrkbys/norimaci/files/4113056/Norimaci_25_Jan_20__15_33_675474.bsm.zip)
`
Thanks

**Comment by mnrkbys** [comment]
Could you upload Norimaci_25_Jan_20__15_33_675474.proclist too?

**Comment by kwiha** [comment]
[out.zip](https://github.com/mnrkbys/norimaci/files/4113792/out.zip)
I've replicated the errors here. his upload contains both. The sample I run was 4d86ae25913374cfcb80a8d798b9016e should you want to recreate the error locally. Thanks

**Comment by mnrkbys** [comment]
Thanks @kwiha, I've already found a root cause of the bug.
But let me sleep for a while, please. It's 2:40 am now in Japan...

**Comment by mnrkbys** [comment]
The issue has been fixed.
