### ISSUE TITLE
New parsing error

### ISSUE THREAD

**Issue by kwiha** [mnrkbys/norimaci#2]
Hi, thanks for fixing. looks like there's a new issue. maybe Im doing something wrong

tester@testers-Mac norimaci % sudo python3 ./norimaci.py -m openbsm -o ./out/
Password:

--===[ Norimaci v0.1.0
--===[ Minoru Kobayashi [@unkn0wnbit]
[*] Launching OpenBSM agent...
[*] When runtime is complete, press CTRL+C to stop logging.
^C
[*] Termination of OpenBSM agent commencing... please wait
[*] Converting OpenBSM data ...
Traceback (most recent call last):
  File "/Users/tester/Downloads/norimaci/./openbsmconv.py", line 875, in <module>
    sys.exit(main())
  File "/Users/tester/Downloads/norimaci/./openbsmconv.py", line 852, in main
    bsm_events_json = convert_bsm_events(file_openbsm_log)
  File "/Users/tester/Downloads/norimaci/./openbsmconv.py", line 524, in convert_bsm_events
    tag_attr = get_attributes(['exec arg', 'path', 'subject', 'return'], payload)
  File "/Users/tester/Downloads/norimaci/./openbsmconv.py", line 294, in get_attributes
    _tag, payload = payload.split(',', 1)
ValueError: not enough values to unpack (expected 2, got 1)
[!] Fatal: Failed to run data converter: Command '['python3', '/Users/tester/Downloads/no
rimaci/./openbsmconv.py', '-p', '/Users/tester/Downloads/norimaci/out/Norimaci_25_Jan_20_
_19_34_499040.proclist', '--with-failure-socket', '-f', '/Users/tester/Downloads/norimaci
/out/Norimaci_25_Jan_20__19_34_499040.bsm', '-o', '/Users/tester/Downloads/norimaci/out/N
orimaci_25_Jan_20__19_34_499040.json', '--force']' returned non-zero exit status 1.
[out.zip](https://github.com/mnrkbys/norimaci/files/4118438/out.zip)

**Comment by mnrkbys** [comment]
Thanks for your report.
I've fixed this issue.
